ci/cd:
- all:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

app:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'

tests:
- all:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/**/*'  

documentation:
- all:
  - changed-files:
    - any-glob-to-any-file: ['*.md*', '**/*.md*']
