<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Combinators.fs" />
    <Compile Include="Exception.fs" />
    <Compile Include="String.fs" />
    <Compile Include="Option.fs" />
    <Compile Include="Environment.fs" />
    <Compile Include="Task.fs" />
    <Compile Include="Json.fs" />
    <Compile Include="Io.fs" />
    <Compile Include="Colours.fs" />
  </ItemGroup>

</Project>
