<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models.fs" />
    <Compile Include="Markdown.fs" />
    <Compile Include="MarkdownReporting.fs" />
    <Compile Include="JsonReporting.fs" />
    <Compile Include="Console.fs" />
    <Compile Include="ConsoleReporting.fs" />
    <Compile Include="GithubReporting.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\pkgchk.core\pkgchk.core.fsproj" />
  </ItemGroup>

</Project>
