<Project>

  <PropertyGroup>
    <Copyright>Copyright 2023 Tony Knight</Copyright>
    <Authors>Tony Knight</Authors>
    <Product>Dependency checks</Product>
    <Description>Tooling for .NET dependency checks</Description>
    <RepositoryUrl>https://github.com/tonycknight/pkgchk-cli</RepositoryUrl>
    <PackageProjectUrl>https://github.com/tonycknight/pkgchk-cli</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>nuget;sca;dependencies;vulnerabilities;deprecations;ci/cd</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Data" Version="8.1.14" />
    <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="Spdx" Version="0.11.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="Tk.Nuget" Version="0.3.1" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />    
  </ItemGroup>
  
</Project>
