name: Pull Request checks

permissions: # set permissions to principle of least privilege, codeql requires read permission to the repo content and PRs (if that option is set), and must have write permissions to security events in order to push results
  actions: read
  pull-requests: write
  security-events: write
  contents: write
  checks: write

on:
  pull_request:
    
jobs:
  style-rules:
    name: Check style rules
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        
      - name: Tool restore
        run: dotnet tool restore
      
      - name: App restore
        run: dotnet restore

      - name: Check style
        run: dotnet fantomas  ./ --check 

  pr-scope:
    name: Set PR scope
    runs-on: ubuntu-latest
    needs: [ size-label ]
    steps:
      - uses: actions/labeler@v5
        name: Set label
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  size-label:
    name: Set change size
    runs-on: ubuntu-latest
    steps:
      - name: Set label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "1": "XS",
              "10": "S",
              "20": "M",
              "50": "L",
              "100": "XL"
            }


